name: call docker action in another repo
on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: run docker action
        uses: mymmym1/hello-world-docker-action@v1
        with:
          who-to-greet: '@wulfland'
    
