name: Reusable workflow
on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'The person to greet'
        type: string
        required: true
        default: World
     
    outputs:
      current-time:
        description: 'The time when greeting.'
        value: ${{ jobs.reusable-job.outputs.current-time }}

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ steps.time.outputs.time }}
      
    steps:
      - name: Greet someone
        run: echo "Hello ${{ inputs.who-to-greet }}"

      - name: Set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: mymmym1/githubtrainning20240117
          ref: main
          
      - name: Check current workspace
        run: ls

      - name: Pull PowerShell Docker image
        run: docker pull mcr.microsoft.com/powershell:latest

      - name: Run PowerShell Script
        run: |
          docker run -v "$(pwd):/workspace" mcr.microsoft.com/powershell:latest pwsh -c "ls /workspace"
          docker run -v "$(pwd):/workspace" mcr.microsoft.com/powershell:latest pwsh -File /workspace/my-powershell-action/echo-message.ps1 -message 'Hello, GitHub Actions!'

   
